apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: logging-monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: app
        image: busybox
        command: ["sh", "-c"]
        args:
          - |
            while true; do
              echo "$(date) [INFO] Application is running"
              echo "$(date) [ERROR] Simulated error message" >&2
              sleep 5
            done