apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  namespace: tutorial
  labels:
    app: secret-app
    tutorial: configuration
spec:
  containers:
  - name: app
    image: busybox:latest
    command: ["/bin/sh", "-c", "sleep 3600"]
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: password
    envFrom:
    - secretRef:
        name: app-secret
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secrets
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: app-secret

