apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: tutorial
type: Opaque
data:
  username: YWRtaW4=  # base64 encoded "admin"
  password: cGFzc3dvcmQxMjM=  # base64 encoded "password123"
  api-key: YWJjZGVmZ2hpams=  # base64 encoded "abcdefghij"

