apiVersion: v1
kind: Pod
metadata:
  name: affinity-pod
  namespace: tutorial
  labels:
    app: affinity-app
    tutorial: advanced
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: zone
            operator: In
            values:
            - us-east-1
  containers:
  - name: app
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"

