apiVersion: v1
kind: Pod
metadata:
  name: anti-affinity-pod
  namespace: tutorial
  labels:
    app: anti-app
    tutorial: advanced
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: zone
            operator: NotIn
            values:
            - us-west-1
  containers:
  - name: app
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"

