apiVersion: v1
kind: LimitRange
metadata:
  name: tutorial-limits
  namespace: tutorial-resources
spec:
  limits:
  - default:
      memory: "256Mi"
      cpu: "200m"
    defaultRequest:
      memory: "128Mi"
      cpu: "100m"
    max:
      memory: "512Mi"
      cpu: "500m"
    min:
      memory: "64Mi"
      cpu: "50m"
    type: Container

