apiVersion: v1
kind: Pod
metadata:
  name: large-pod
  namespace: tutorial-resources
  labels:
    app: large-app
    tutorial: resource-management
spec:
  containers:
  - name: app
    image: nginx:latest
    resources:
      requests:
        memory: "3Gi"  # Exceeds quota of 2Gi
        cpu: "3"       # Exceeds quota of 2
      limits:
        memory: "4Gi"
        cpu: "4"

